"""
Email Notification System — with dynamic APP_URL support
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def _get_config():
    try:
        from app.config import settings
        return {
            "smtp_host":       settings.EMAIL_SMTP,
            "smtp_port":       settings.EMAIL_PORT,
            "from_email":      settings.EMAIL_FROM,
            "from_pass":       settings.EMAIL_PASSWORD,
            "notify_critical": settings.NOTIFY_ON_CRITICAL,
            "app_url":         settings.APP_URL,
        }
    except Exception as e:
        print(f"[Email] Config load error: {e}")
        return {
            "smtp_host":       "smtp.gmail.com",
            "smtp_port":       587,
            "from_email":      "",
            "from_pass":       "",
            "notify_critical": True,
            "app_url":         "http://localhost:5173",
        }


def _app_url() -> str:
    return _get_config()["app_url"]


def _send(to: str, subject: str, html: str) -> bool:
    cfg        = _get_config()
    from_email = cfg["from_email"]
    from_pass  = cfg["from_pass"]

    if not from_email or not from_pass:
        print(f"[Email] Skipped (no credentials in .env)")
        print(f"[Email]   EMAIL_FROM={repr(from_email)}")
        print(f"[Email]   EMAIL_PASSWORD={'set' if from_pass else 'EMPTY'}")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = f"NeuralOnco <{from_email}>"
        msg["To"]      = to
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(cfg["smtp_host"], cfg["smtp_port"]) as s:
            s.ehlo()
            s.starttls()
            s.login(from_email, from_pass)
            s.sendmail(from_email, to, msg.as_string())

        print(f"[Email] ✓ Sent to {to}: {subject}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("[Email] ✗ Authentication failed — wrong App Password or Gmail blocked")
        return False
    except smtplib.SMTPConnectError:
        print(f"[Email] ✗ Cannot connect to SMTP server")
        return False
    except Exception as e:
        print(f"[Email] ✗ Failed: {e}")
        return False


def _base_template(title: str, body: str, color: str = "#00D4FF") -> str:
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="margin:0;padding:0;background:#080B1A;font-family:Arial,sans-serif;color:#E8EEFF;">
  <div style="max-width:560px;margin:32px auto;background:#0D1128;border-radius:16px;border:1px solid rgba(0,212,255,0.2);overflow:hidden;">
    <div style="background:linear-gradient(135deg,#7B2FFF,#00D4FF);padding:24px 32px;">
      <h1 style="margin:0;font-size:22px;color:#fff;letter-spacing:1px;">NeuralOnco</h1>
      <p style="margin:4px 0 0;font-size:13px;color:rgba(255,255,255,0.8);">Brain Tumor Detection System v2.4.1</p>
    </div>
    <div style="background:{color}18;border-bottom:2px solid {color};padding:16px 32px;">
      <h2 style="margin:0;font-size:18px;color:{color};">{title}</h2>
    </div>
    <div style="padding:28px 32px;">{body}</div>
    <div style="padding:16px 32px;background:#080B1A;border-top:1px solid rgba(0,212,255,0.1);">
      <p style="margin:0;font-size:11px;color:#6B7DB3;text-align:center;">
        Generated by NeuralOnco · {datetime.now().strftime('%d %b %Y %H:%M')} · Do not reply to this email.
      </p>
    </div>
  </div>
</body>
</html>"""


def _row(label: str, value: str) -> str:
    return f'<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid rgba(0,212,255,0.1);"><span style="color:#6B7DB3;font-size:13px;">{label}</span><span style="color:#E8EEFF;font-size:13px;font-weight:600;">{value}</span></div>'


def _btn(text: str, url: str, color: str = "linear-gradient(135deg,#7B2FFF,#00D4FF)") -> str:
    return f'<div style="margin-top:20px;text-align:center;"><a href="{url}" style="display:inline-block;padding:12px 28px;background:{color};color:#fff;text-decoration:none;border-radius:30px;font-size:13px;font-weight:600;">{text}</a></div>'


# ── Public functions ───────────────────────────────────────────────────

def send_welcome(doctor_email: str, doctor_name: str, hospital: str = "") -> bool:
    url  = _app_url()
    body = f"""
    <p style="font-size:15px;color:#E8EEFF;margin:0 0 16px;">Welcome to NeuralOnco, <strong>{doctor_name}</strong>!</p>
    <p style="font-size:13px;color:#6B7DB3;line-height:1.7;margin:0 0 20px;">
      Your doctor account has been created. You can now register patients, upload MRI scans, and get AI-powered tumor analysis.
    </p>
    {_row("Name", doctor_name)}
    {_row("Email", doctor_email)}
    {_row("Hospital", hospital or "—")}
    {_row("Account Created", datetime.now().strftime("%d %b %Y"))}
    {_btn("Open NeuralOnco →", url)}
    """
    return _send(doctor_email, "Welcome to NeuralOnco — Account Created", _base_template("Account Created Successfully", body, "#00FF94"))


def send_patient_registered(doctor_email: str, patient_name: str, patient_code: str, priority: str = "Normal") -> bool:
    url   = _app_url()
    color = "#FF4757" if priority == "Emergency" else "#FFB800" if priority == "Urgent" else "#00D4FF"
    body  = f"""
    <p style="font-size:14px;color:#E8EEFF;margin:0 0 16px;">A new patient has been registered in the system.</p>
    {_row("Patient Name", patient_name)}
    {_row("Patient ID", patient_code)}
    {_row("Priority", priority)}
    {_row("Registered", datetime.now().strftime("%d %b %Y %H:%M"))}
    {_btn("Go to MRI Scan →", f"{url}/mri-scan")}
    """
    return _send(doctor_email, f"New Patient Registered — {patient_name}", _base_template(f"Patient {patient_code} Registered", body, color))


def send_scan_result(
    doctor_email: str, patient_name: str, patient_code: str,
    scan_id: int, status: str, confidence: float,
    tumor_type: str, tumor_grade: str, location: str, recommendation: str,
) -> bool:
    url    = _app_url()
    color  = "#FF4757" if status == "Malignant" else "#FFB800" if status == "Benign" else "#00D4FF" if status == "Pituitary" else "#00FF94"
    urgent = status == "Malignant"
    subject = f"{'🚨 URGENT — ' if urgent else ''}MRI Analysis Complete — {patient_name} ({status})"
    urgent_banner = "<div style='background:#FF475722;border:1px solid #FF475766;border-radius:10px;padding:12px 16px;margin-bottom:20px;'><p style='margin:0;color:#FF4757;font-size:13px;font-weight:600;'>⚠ URGENT: Malignant tumor detected. Immediate consultation required.</p></div>" if urgent else ""

    body = f"""
    {urgent_banner}
    <p style="font-size:14px;color:#E8EEFF;margin:0 0 16px;">AI analysis completed for <strong>{patient_name}</strong>.</p>
    {_row("Patient", f"{patient_name} ({patient_code})")}
    {_row("Scan ID", f"SC-{scan_id}")}
    {_row("Diagnosis", status)}
    {_row("AI Confidence", f"{confidence:.1f}%")}
    {_row("Tumor Type", tumor_type or "—")}
    {_row("WHO Grade", tumor_grade or "—")}
    {_row("Location", location or "—")}
    {_row("Analysis Date", datetime.now().strftime("%d %b %Y %H:%M"))}
    <div style="margin-top:16px;padding:14px 16px;background:rgba(255,184,0,0.08);border-radius:10px;border:1px solid rgba(255,184,0,0.2);">
      <p style="margin:0 0 6px;font-size:12px;color:#FFB800;font-weight:600;">⚕ Clinical Recommendation</p>
      <p style="margin:0;font-size:12px;color:#6B7DB3;line-height:1.6;">{recommendation}</p>
    </div>
    {_btn("View Full Report →", f"{url}/patient/{patient_code}")}
    """
    return _send(doctor_email, subject, _base_template(f"MRI Analysis — {status}", body, color))


def send_critical_alert(
    doctor_email: str, patient_name: str, patient_code: str,
    confidence: float, tumor_type: str,
) -> bool:
    cfg = _get_config()
    if not cfg["notify_critical"]:
        return False
    url  = cfg["app_url"]
    body = f"""
    <div style="background:#FF475722;border:2px solid #FF4757;border-radius:12px;padding:20px;margin-bottom:20px;">
      <p style="margin:0;color:#FF4757;font-size:16px;font-weight:700;">🚨 CRITICAL FINDING DETECTED</p>
      <p style="margin:8px 0 0;color:#E8EEFF;font-size:13px;">Immediate medical attention may be required.</p>
    </div>
    {_row("Patient", f"{patient_name} ({patient_code})")}
    {_row("Finding", "Malignant Tumor")}
    {_row("Tumor Type", tumor_type or "—")}
    {_row("AI Confidence", f"{confidence:.1f}%")}
    {_row("Alert Time", datetime.now().strftime("%d %b %Y %H:%M"))}
    <p style="margin-top:16px;font-size:13px;color:#6B7DB3;line-height:1.7;">
      Please review this patient's scan immediately and consult with a neurosurgeon or oncologist.
    </p>
    {_btn("View Patient Now →", f"{url}/patient/{patient_code}", "linear-gradient(135deg,#FF4757,#FF8C00)")}
    """
    return _send(doctor_email, f"🚨 CRITICAL ALERT — Malignant Tumor Detected in {patient_name}", _base_template("Critical Finding Alert", body, "#FF4757"))